const YELP_FUSION_TOKEN = 'Mvo2QTUxWOtTekDksTnqmLvdHOTzY28k8UYuH9svFl1RQgCzwbyHy9T2G38MXVhfMv9NEpBDSrbChPKMvVtAh4tw9CCIg6sYD7_koosGyBxQ0iaZLDJP7mLO8OVOXnYx';

module.exports = { YELP_FUSION_TOKEN };
